FROM gcc
RUN apt-get update && apt-get install -y \
    make git
WORKDIR /befunge
RUN rm -rf app
RUN git clone https://github.com/catseye/Befunge-93.git app
WORKDIR /befunge/app
RUN make
RUN cp ./bin/bef /usr/bin/bef
WORKDIR /del
ONBUILD COPY . .
CMD ["bash", "-c", "bef app/main.bf"]