# Jenkins Admin role
jenkins_role_admin_name: admin
jenkins_role_admin_description: Thanos

# Jenkins Admin user
# credentials in vault

jenkins_additional_env: >

# listen ports for the different services
# accepted formats for ports: 4242, 127.0.0.1:4242 (e.g. only listens localhost)
jenkins_http_port: 4242
jenkins_controller_port: 50000
docker_registry_port: 5000

# host used for every commands run by Jenkins and Kubectl such as: docker push HOST/image, docker pull HOST/image
# if you use external kubernetes nodes, you might want to use another ip (public ip or shared network) instead of localhost!
docker_registry_host: localhost:5000
# credentials in vault
docker_registry_additional_env: >