services:
  jenkins:
    build:
      context: .
      args:
        - DOCKER_REGISTRY_HOST=${DOCKER_REGISTRY_HOST}
        - DOCKER_REGISTRY_USER=${DOCKER_REGISTRY_USER}
    restart: always
    privileged: true
    security_opt:
      - label=disable
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yml
    env_file:
      - .env
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
      - "${JENKINS_CONTROLLER_PORT}:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./jenkins-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./kubeconfig.yml:/var/jenkins_home/kubeconfig.yml:ro
      - ../images:/opt/images:ro
      - ../tools:/opt/tools:ro
    networks:
      - jenkins

networks:
  jenkins:
    name: jenkins

volumes:
  jenkins-data: